### PR TITLE
traverse: Apply -> Applicative

### PR DESCRIPTION
**Pull request by tycho01**
afaict this was a typo. very confusing for learners like me. :<

### CODE REVIEW

**Comment by safareli** [comment]
Yes it's a typo
>     2. `f` must return a value of an Applicative

**Comment by rpominov** [comment]
See also https://github.com/fantasyland/fantasy-land/pull/147/files#r79309177

**Comment by safareli** [comment]
@rpominov as you pointed out maybe we should change laws so it's consistent with type signature?

Or we could change the method to something like this?
```
traverse :: Applicative f, Traversable t => t a ~> (TypeRep f, a -> f b) -> f (t b)
```

Or we need to add FAQ.md 😄

**Comment by rpominov** [comment]
Yea, +1 to at lest make it consistent.

**Comment by safareli** [comment]
For `Tuple z a` user could provide function of form `a ->  Tuple z a`  (for example `(a) => Tuple([], a)`) and I think it would work properly. So we should change `Applicative` to `Apply` in law?
or use `TypeRep f` instead of passing `a -> f a`? @SimonRichardson @davidchambers @scott-christopher

**Comment by scott-christopher** [comment]
As per the comment @rpominov linked to above, my original thoughts were to use the weaker constraints of `Apply` given that `of` had to be explicitly passed anyway meaning it was already described in the signature.

Now that we have the language to describe `Applicative f => TypeRep f`, it could make it clearer to ask for the full `TypeRep` now rather than just the `of` function.

**Comment by rpominov** [comment]
> Now that we have the language to describe Applicative f => TypeRep f, it could make it clearer to ask for the full TypeRep now rather than just the of function.

That a good idea for the future. Btw this is how it's done in static-land, so we should get this automatically if [unification](https://github.com/fantasyland/fantasy-land/issues/199) happen.

But for now we should at least fix the inconsistency: either make a change in the signature or in laws.

**Comment by scott-christopher** [comment]
> But for now we should at least fix the inconsistency: either make a change in the signature or in laws.

Sure, in that case I'm personally happy with this PR as it is.

**Comment by davidchambers** [comment]
> Now that we have the language to describe `Applicative f => TypeRep f`, it could make it clearer to ask for the full `TypeRep` now rather than just the `of` function.

I'm in favour of this change. It's beyond the scope of this pull request, though.

**Comment by safareli** [comment]
@fantasyland/core if others think this is the way to go please approve this.

**Comment by joneshf** [comment]
Thanks so much @tycho01 and every involved!

**Pull request merged**
