### PR TITLE
Add zoom as an implementation.

### PR DESCRIPTION
**Pull request by dustinws**
Hello all,

I've added a library I maintain in my downtime to the implementations file, let me know what you guys think!

So far it supports a few different types, with a strong focus on documentation and examples. Since it's just me working on it right now, the examples still have a long way to go. In the documentation, each type is explicit about the fantasy types they conform to.

Thanks!

If you would like a link to the library without looking through the diff, [here it is](https://dustinws.github.io/zoom/index.html).

### CODE REVIEW

**Comment by davidchambers** [comment]
I'm happy to include this, although I'm always a little saddened to see new implementations of algebraic data types for which lawful implementations already exist. :cry:

**Comment by gabejohnson** [comment]
@dustinws cool lib!

I took a quick glance and I'm not sure all of your types implement all of algebras lawfully. I can submit an issue if you'd like.

**Comment by dustinws** [comment]
@davidchambers I absolutely agree with your point. In it's current state, the library doesn't offer anything that isn't already found in other implementations.

I feel your tear(s), but I hope you can trust that I intend to do much more with this project. If I planned on leaving it as is, I'd skip the PR and just use an existing library.

If you would prefer that I leave this out until it can set itself apart from other libraries, then I'm happy to do that. I was hoping that putting it in the implementations file would get the name out there and potentially get some other contributors.

Thanks for the super quick response!

**Comment by dustinws** [comment]
@gabejohson that would be great! The initial beta was done in a bit of a rush, so It would be a huge help for you to point out anything that doesn't look right.

**Comment by davidchambers** [comment]
> I was hoping that putting it in the implementations file would get the name out there and potentially get some other contributors.

This is the thing that saddens me. The JavaScript functional programming community is relatively small, and our resources are limited. I would love to see contributions to Fluture, Folktale, Sanctuary, etc. rather than new libraries which duplicate existing functionality (and in some cases violate laws).

**Comment by dustinws** [comment]
@davidchambers I see your point. I'm new to the open source community and I could definitely be putting effort into other projects. I was a bit put off by my initial attempt, I have an issue open in another implementation that hasn't gotten a single reply in over six months, and I think that reinforced my DIY attitude.

With that said, I really do think this library will separate itself from other implementations, and warrant it's own space. If I'm wrong about this, then I'll happily eat my words.

My biggest goal is providing an easy transition from procedural / imperative programming. It seems like most implementations are focused on purity, while I want to focus on accessibility.

I'm not much of a writer, so I'd rather not write blogs or something similar. I think this is my way of trying to teach people what I've learned so far by using conversational documentation, and real world examples, with a strong sense of consistency across the whole library.

As some backstory, I tried to show off another FL implementation to another dev at my company. He took one look at the docs before dismissing it as an academic novelty. This is what I want to avoid. It's not a responsibility I want to put on other projects, so that's why i'm doing it here. In some way, I feel like I've "joined the club". Now I want others to join, and I want to remove as much of the intimidation as possible.

If anyone believes they understand my goal and know of a _better_ way to achieve it (without blogs), I'm definitely open to that discussion.

Like I said, I'm new here!

**Comment by davidchambers** [comment]
I don't mean to be discouraging, @dustinws, and I commend you for taking action to share the benefits of functional programming with the broader JavaScript community. Your goals are very much in line with those of @JAForbes. The two of you may be interested in sharing ideas.

**Comment by dustinws** [comment]
@davidchambers I appreciate the mention, I'm definitely interested in linking up with others. Also, I don't really find it discouraging, I can see that you care about improving the existing community / projects and I think that's an awesome thing.

I'm going to continue working on this library, at least until I've implemented the pending types I have. This part is a personal endeavor, since implementing something and then having to write the docs / examples has proven to be the best way to really learn the internals of something. I'm still in the learning stage, and this is my way of solidifying everything.

If you would rather hold off on merging this in, there's definitely no hard feelings on my end. Though I must admit, it would be sweet to represent the FL logo.

Either way, you have sparked my interest in getting involved with other projects. I'm going to do more research on the existing ecosystem and see what needs to be done, I'd love to help out.

**Comment by davidchambers** [comment]
> This part is a personal endeavor, since implementing something and then having to write the docs / examples has proven to be the best way to really learn the internals of something.

I couldn't agree more. :)

> Either way, you have sparked my interest in getting involved with other projects. I'm going to do more research on the existing ecosystem and see what needs to be done, I'd love to help out.

I'm thrilled to hear this! You may be interested in joining some or all of these Gitter rooms:

  - [Fantasy Land](https://gitter.im/fantasyland/fantasy-land)
  - [Fluture](https://gitter.im/fluture-js/Fluture)
  - [Folktale](https://gitter.im/folktale/discussion)
  - [Sanctuary](https://gitter.im/sanctuary-js/sanctuary)

You're also welcome to contact me directly via Gitter or email.

**Comment by dustinws** [comment]
Closing this guy out for now. I've been pretty busy with work, so I haven't been able to anything new lately. Once I get some new stuff and set this project apart from others i'll be back!

Also @davidchambers I hopped on the FL and Fluture gitters, I'll pop in and say hello soon (and join the others). Looking forward to helping out where I can.

**Pull request closed without merging**
