### PR TITLE
Unbreak things

### PR DESCRIPTION
**Pull request by isiahmeadows**
Now the tests actually pass. Apparently, namespacing things apparently was a real *breaking* change... :wink:

### CODE REVIEW

**Comment by rpominov** [comment]
How do you run those tests btw? :)

**Comment by isiahmeadows** [comment]
@rpominov 

- Node 6+: `nodeunit id_tests.js` (it complains about `--harmony_destructuring` being invalid)
- Node 5 and before: `npm test`

**Comment by isiahmeadows** [comment]
It basically tests the `Id` type that comes with this, and verifies that it passes the laws. IIUC it also helps as a sanity check to ensure the laws are actually consistent as well.

**Comment by rpominov** [comment]
Ah right, there is an `npm test` script, sorry. And sorry for breaking things :)

**Comment by isiahmeadows** [comment]
@rpominov You're okay. It's just that there isn't CI, and no one until now bothered to run the tests.

**Comment by rpominov** [comment]
Would be cool to setup Travis btw.

**Comment by isiahmeadows** [comment]
Ping @SimonRichardson?

**Comment by SimonRichardson** [comment]
Travis next 👍

**Comment by isiahmeadows** [comment]
Thanks!

**Pull request merged**
