### PR TITLE
change Monoid#empty from nullary function to identity element itself

### PR DESCRIPTION
**Pull request by michaelficarra**
:sweat_smile:

### CODE REVIEW

**Comment by puffnfresh** [comment]
:neutral_face:

**Comment by 5outh** [comment]
I think I'm in favor of this, does it screw with anything? @puffnfresh

**Comment by puffnfresh** [comment]
No preference. Can construct an argument either way.

**Comment by SimonRichardson** [comment]
Question: should changes like this PR also fix all the other fantasy-land repos?

**Comment by 5outh** [comment]
On second thought, changing the spec from how it was may cause other peoples' projects to no longer conform to the spec and if there's no preference either way, I think we should keep it the way it is.

**Comment by SimonRichardson** [comment]
@michaelficarra what are the reasons behind this i.e. what's the motivation other than it looks nicer?

**Comment by joneshf** [comment]
We're semver'ing this thing, so we could just bump the version.

**Comment by 5outh** [comment]
I think @SimonRichardson has a point, we should keep all of the fantasy-repositories up to date with the latest version, which is kind of unfortunate.

Should we take this to a vote or something?

**Comment by davidchambers** [comment]
This approach is incompatible with the current [Id implementation][1]:

> ```javascript
> // Monoid (value must also be a Monoid)
> Id.prototype.empty = function() {
>     return new Id(this.value.empty ? this.value.empty() : this.value.constructor.empty());
> };
> ```


[1]: https://github.com/fantasyland/fantasy-land/blob/master/id.js

**Comment by SimonRichardson** [comment]
Can we close this, it doesn't seem to over any value and consider it could break implementations I don't see the point. I hope you don't mind?

**Pull request closed without merging**
