### PR TITLE
Added 'then' (>>) specs

### PR DESCRIPTION
**Pull request by TrevorBasinger**
This is for issue #83 .

### CODE REVIEW

**Comment by michaelficarra** [comment]
This is not the spec, it is just a sample implementation. And I agree with @5outh from #83: this function should be derived, not implemented individually by each Monad.

**Comment by 5outh** [comment]
Right, the point of fantasy-land is to guide implementations of various structures. What I meant in #83 was that mentioning `then` in the specification as a derivable function is not necessarily a bad idea, as long as it goes along with the document nicely.

**Comment by TrevorBasinger** [comment]
@5outh Oh, I think I understand now. @michaelficarra You're correct, I completely over looked the spec.

If you guys wouldn't mind, would you please expand on why you'd rather see it derived instead of implemented on monads? I'm still fairly new to FP. I'm curious why Haskell implements return and two forms of bind, but in this situation it doesn't make sense. (or is >> derived in Haskell somewhere?)

From a "using fantasyland" perspective, it seems like it would be something that is useful. Admittedly, Promises are the only use case I can think of at the moment. But I attribute that to my lack of experience.

**Comment by michaelficarra** [comment]
It is derived in Haskell. Here is an excerpt from [the source](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Base.html#%3E%3E):

```hs
    {-# INLINE (>>) #-}
    m >> k      = m >>= \_ -> k
```

We're not saying it's not useful, but that it should only be implemented once, ever.

**Comment by puffnfresh** [comment]
```js
function then(a, b) {
  return a.chain(function(ignored) {
    return b;
  });
}
```

This works for all structures which support Bind. This is the _fundamental_ point of monads - being able to write these functions only once. Code reuse!

**Pull request closed without merging**
