### PR TITLE
Fix: map derivated from ap and of

### PR DESCRIPTION
**Pull request by shfshanyue**
it may be this from what i understand. for example 

``` js
const add = x => x + 1
[1, 2, 3, 4, 5].map(add)      // [2, 3, 4, 5, 6]
Array.of(add).ap([1, 2, 3, 4, 5]) // [2, 3, 4, 5, 6]
```

### CODE REVIEW

**Comment by safareli** [comment]
[ap :: Apply f => f a ~> f (a -> b) -> f b](https://github.com/fantasyland/fantasy-land#ap-method)

**Comment by davidchambers** [comment]
Do you know which source led you to this understanding, @shfshanyue? Perhaps ramda-fantasy or another library still targeting an old version of the Fantasy Land spec?

**Comment by shfshanyue** [comment]
``` js
Array.prototype.ap = function (xs) {
  return this.reduce((acc, f) => acc.concat(xs.map(f)), [])
}
```

@davidchambers  it's it...

**Comment by davidchambers** [comment]
Where did you find that snippet, @shfshanyue?

**Comment by shfshanyue** [comment]
[applicative-functor](https://github.com/hemanth/functional-programming-jargon#applicative-functor)

thanks very much, @davidchambers

**Comment by davidchambers** [comment]
That's in line with `ap` as it was defined prior to #145.

**Pull request closed without merging**
