### PR TITLE
equivalent promises

### PR DESCRIPTION
**Pull request by Bamieh**
Two promises are equivalent when they yield equivalent values *for equivalent inputs*.

### CODE REVIEW

**Comment by rpominov** [comment]
What is input for a promise? Promises just contain values, there is no input.

**Comment by Bamieh** [comment]
@rpominov So bare with me here, what is a promise? a promise is a function that takes a resolver function as input and calls it passing `resolve` and `reject` to the `resolver` as params. hence when calling:

```
var a = new Promise(function resolver(resolve, reject) {
   resolve('value');
});
```

The input is the `resolver` function here. and for two promises to be equally the same, the input `resolver` functions must be equivalent.

The Promise return must be equivalent as well, which is something similar to

```
Promise {<resolved>: "value"}
```

And the promise yield is the result returned in the `then` payload, this also must be equivalent.

Looking at v8 code, here is how a promise is defined:

```
var $Promise = function Promise(resolver) {
  if (resolver === promiseRaw) return;
  if (!%_IsConstructCall()) throw MakeTypeError('not_a_promise', [this]);
  if (!IS_SPEC_FUNCTION(resolver))
...
///src: https://chromium.googlesource.com/v8/v8/+/3.29.45/src/promise.js?autodive=0%2F#38
```


hence comes my definition of a promise input.

**Comment by rpominov** [comment]
I think we're confusing the Promise constructor and promise instances. Yes, the *promise constructor* is a function that takes a resolver and returns a *promise instance*. And specification talks about promise instances.

**Comment by Bamieh** [comment]
@rpominov yes indeed, as the only way to interact with a promise instance is to use call a new promise.  In this case, a promise instance is a plain object with differing `[[PromiseResult]]` internal slot values when they resolve.

I will close, thanks for your time.

**Comment by Bamieh** [comment]
@CrossEye thanks, i'll have a look at it

**Pull request closed without merging**
