### PR TITLE
feat: replace dependency picture with a hyperlink map

### PR DESCRIPTION
**Pull request by jceb**
I added the hyperlink map from sanctuary-type-classes as I find it much easier to navigate and consume than the two-fold link list + dependency picture.

### CODE REVIEW

**Comment by CrossEye** [comment]
This is a great improvement!

Note that there is a typo in the semigroupoid link.

**Comment by davidchambers** [comment]
Several people raised concerns when I proposed this change in #160.

**Comment by jceb** [comment]
Hm, shall we include both, i.e. restore the list, restore the figure and place the pre-formatted map below?

**Comment by davidchambers** [comment]
@joneshf was concerned about maintenance; perhaps he will chime in. Maintaining the graph in sanctuary-type-classes has not proven onerous. We have a [script][1] that automatically updates the readme as part of the release process, and the [source][2] is easy to edit in Vim or any other editor with a block mode. Furthermore, changes have not been necessary for several years.

I am in favour of the proposed change, but I think we should incorporate a modified version of the aforementioned script.


[1]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v12.1.0/scripts/generate-readme
[2]: https://github.com/sanctuary-js/sanctuary-type-classes/blob/v12.1.0/index.js#L34-L66

**Comment by joneshf** [comment]
Sorry, I thought I'd responded to this.

I don't really have an opinion on this stuff these days. I say, do what makes sense to you all.

**Review by davidchambers — APPROVED** [review]

**Comment by davidchambers** [comment]
I'm in favour of this change, @jceb. Is this pull request up to date? I see that it has been open for more than two years. :sob:

**Comment by jceb** [comment]
Let me double check😀

**Comment by jceb** [comment]
I rebased the PR. It's now up-to-date.

**Review by diasbruno — APPROVED** [review]

**Pull request merged**
