### PR TITLE
Add a link to Static Land

### PR DESCRIPTION
**Pull request by rpominov**
Static Land is not intended to be a competitor for Fantasy Land so I thought it might be OK to add the link. /cc @joneshf

### CODE REVIEW

**Comment by SimonRichardson** [comment]
We should move it down to add a header with alternatives, if you don't mind? Then at a later date we can add more details if we want/required.

Otherwise 👍

**Comment by rpominov** [comment]
Done!

**Comment by SimonRichardson** [comment]
Merged

**Comment by rpominov** [comment]
Thanks 😄

**Comment by SimonRichardson** [comment]
Need to merge others as well tbh...

**Comment by rpominov** [comment]
Everything is ready in both on my side. There might be a conflict though because both touch `laws/*.js` files. But I'm happy to resolve the conflicts after one is merged of course.

**Comment by SimonRichardson** [comment]
Think I wanted just another member ok on the ap flip one. Then we can merge
the spec change one.

**Comment by joneshf** [comment]
Sorry, I've been sort of in and out. If you need another set of eyes, mention me.

**Comment by joneshf** [comment]
Also, HECK YEAH!

**Pull request merged**
