### PR TITLE
derive index.js and index.d.ts from canonical list of method names

### PR DESCRIPTION
**Pull request by davidchambers**
This pull request supersedes #270, which included a few unrelated changes which have since been rendered unnecessary (#293).

Like #270, this pull request avoids npm dependencies by using standard Unix programs to generate __index.d.ts__. The `awk` script is just a single line:

```bash
awk '{ print "export const " $0 ": \047fantasy-land/" $0 "\047;" }' names >index.d.ts
```

Unlike #270, this pull request uses [string literal types][1] in __index.d.ts__ rather than the far less specific [`string`][2] type. I'm not a TypeScript user so I would greatly appreciate a review by @bcherny, @andnp, @sunderhus, or anyone else in the community with TypeScript knowledge. :)

This pull request also updates __CONTRIBUTING.md__ with instructions for updating the various files, and updates the behaviour of `npm run lint` such that ignoring these instructions will result in an error.

[1]: https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types
[2]: https://www.typescriptlang.org/docs/handbook/basic-types.html#string

### CODE REVIEW

**Comment by paldepind** [comment]
Looks good to me. The types are correct and given how simple they are generating them in the proposed manner seems reasonable.

**Comment by bcherny** [comment]
@davidchambers Sounds good. I’m not sure I’d make the same decision, but thanks for taking the time to clarify! TS looks good to me. One note- it looks like the generated JS use ES5-style exports, but the generated TS uses ES6-style exports. If I’m reading that right, I’d suggest sticking to one or the other.

**Comment by davidchambers** [comment]
> One note- it looks like the generated JS use ES5-style exports, but the generated TS uses ES6-style exports. If I’m reading that right, I’d suggest sticking to one or the other.

Restricting the JavaScript file to ES5 syntax enables it to be used as is in environments (such as Node) which don't support `import`/`export`. Given that TypeScript files must necessarily be processed before being evaluated, is there a reason not to use `export` and `const` in that context?

**Comment by bcherny** [comment]
@davidchambers It's just another small deviation from standard TS practice (declare in TS + ES6, compile to JS + ES5 with tsc). Looks good to me!

**Comment by davidchambers** [comment]
> I'm no shell scripting expert, but, is there any reason for not making the scripts `#!/bin/sh` POSIX compatible? As far as I can tell they don't use any bashisms.

I like to understand the code I write, but with shell scripts I'm not averse to cargo cult programming. ;)

This pull request has been open for a year and a half. Let's merge it. I would not oppose a pull request to change the shebangs, but I'm confident `#!/usr/bin/env bash` will not cause us any problems.

**Pull request merged**
